### ISSUE TITLE
Could you introduce what file or folder dish-cfg in emulate.sh is?

### ISSUE THREAD

**Issue by h0lyDuck** [quarkslab/starlink-tools#2]
As mentioned in the title. THX!

**Comment by CarloRamponi** [comment]
Since the dumped image is marked as read-only, the emulator has no partition in which it can write (except for the temporary ones).
For this reason, I've added two "mapped folders", one containing the whole rootfs and one that in my case is mounted instead of the "dish-cfg" partition, with r/w permissions.
You can remove those two lines and everything should work anyway. Still, if you want to add some persistency to experiment inside the emulator and analyze the produced data, you may want to add one or more "mapped folders".

Here is a guide on how you can do it: [https://wiki.qemu.org/Documentation/9psetup](https://wiki.qemu.org/Documentation/9psetup)
