### ISSUE TITLE
emulator didn't find is_production_hardware script

### ISSUE THREAD

**Issue by cn0xroot** [quarkslab/starlink-tools#6]
Hi

when I try to emulator,can find is_production_hardware script

can you show this script file path?

**Comment by cn0xroot** [comment]
```
bash emulate.sh 
qemu-system-aarch64: -virtfs local,path=./disks/dish-cfg,mount_tag=dishcfg,security_model=mapped-xattr: cannot initialize fsdev 'dishcfg': failed to open './disks/dish-cfg': No such file or directory

```

**Comment by CarloRamponi** [comment]
Hello,
The error message you posted is not related to the `is_production_hardware` script.
The error is due to a missing virtual device that I was using to have a persistent partition in which the device was writing stuff.
To fix this you can either create the virtual device `./disks/dish-cfg` or remove that option from the `qemu` command.
